Fix bugged pet sit button.
EQEmu/Server pull request #1119
Opened 2020-08-31 17:44 UTC by noudess

The pet window sit button is often out of sync.  This PR fixes this issue.  Also pet's were frequently still marked as sitting internal to the server due to the owner being attacked, or other issues.  This is because the anim state was not being correctly updated.

I tested the behavior on live and made it match.  A pet on guard will always return to guard after a battle.  A pet sitting, will switch to follow mode after a battle.  This fix is here as well.

After 2 weeks of testing, I no longer see the pet sit button out of sync, and no longer see (harder to see, but can be done with a char in his teens) pet sitting regen while pet is actually standing.

2020-09-01 15:03 UTC, noudess commented
At the behest of @Trust I am currently adding fixes for the taunt button along the same lines.

2020-09-04 10:13 UTC, freyonsecurity commented
I played with this patch for 6 hours nonstop without any problems as a pet magician. Very good improvement!

2020-09-08 20:27 UTC, mackal requested changes

2020-09-08 20:27 UTC, mackal commented on zone/attack.cpp
> +				// fix GUI sit button to be unpressed and stop sitting regen
wrong indention level

2020-09-08 20:51 UTC, noudess commented on zone/pets.cpp
> +				GetAA(aaAnimationEmpathy) >= 3) {
Can you give me how you would code it?  Just replace GetAA or that entire if?

2020-09-08 23:45 UTC, mackal approved these changes

2020-09-19 23:47 UTC, Akkadius approved these changes
Looks great, good work!

2020-09-19 23:48 UTC, merged