RandomPath improvements
EQEmu/Server pull request #1202
Opened 2021-01-31 23:14 UTC by regneq

RandomPath grid type improvement

RandomPath has been changed to the following behavior:

* When stopped at a waypoint, it will now use the waypoint's pause timer if it is non-zero.  If it is zero, it will use the first waypoint's pause timer if that is non-zero.  If both are zero it will use 38 seconds.  Previously it would always use the first waypoint's pause timer if it was non-zero.  This new way is what it should have been from the start, really.

* If any waypoint is flagged as a centerpoint, then the NPCs will always return to that first randomly selected centerpoint waypoint after moving.  I.e. every other move will be to the first waypoint if the bool is set.

If any waypoint has a negative number (-1, -10, etc) in the pause timer. It will not be included in the waypoints to be random.  Instead the npc will just path through it everytime.  This is useful for a path to only select a small area to pause at before returning to it's centerpoints or another random waypoints in between it.

2021-01-31 23:54 UTC, mackal requested changes

2021-01-31 23:54 UTC, mackal commented on zone/waypoints.cpp
> +						wplist wpl = w;
This shouldn't be necessary, just directly access it through the w reference.

2021-01-31 23:54 UTC, mackal commented on zone/waypoints.cpp
> +						wplist wpl = w;
Same here.

2021-02-01 00:56 UTC, mackal approved these changes

2021-02-01 01:30 UTC, KinglyKrab approved these changes

2021-02-01 18:56 UTC, Akkadius approved these changes

2021-02-01 18:56 UTC, merged