[Merchants] Add Merchant databucket functionality.
EQEmu/Server pull request #1415
Opened 2021-06-14 13:20 UTC by KinglyKrab

- Allows server operators to limit merchant items based on data bucket values and comparisons.
- Adds 3 columns, `bucket_name`, `bucket_value`, and `bucket_comparison` to `merchantlist` table.
- Bucket is checked based on `character_id-bucket_name`.
- `bucket_comparison` Values are as follows:
  - `bucket_comparison` 0: `bucket_name` == `bucket_value`.
  - `bucket_comparison` 1: `bucket_name` != `bucket_value`.
  - `bucket_comparison` 2: `bucket_name` >= `bucket_value`.
  - `bucket_comparison` 3: `bucket_name` <= `bucket_value`.
  - `bucket_comparison` 4: `bucket_name` > `bucket_value`.
  - `bucket_comparison` 5: `bucket_name` < `bucket_value`.

2021-06-16 07:09 UTC, splose approved these changes
This was created towards the end of RoN and was very useful in creating custom progression merchants or simply hiding stuff from clients.

2021-06-18 03:39 UTC, mackal requested changes

2021-06-18 03:39 UTC, mackal commented on zone/client.h
> +enum MerchantBucketComparison {
this should be an `enum class` rather than plain enum. (Eventually I would like to switch all enums over, unless they really don't make sense to)

2021-06-18 03:39 UTC, mackal commented on zone/client_process.cpp
> +		if (bucket_name.length() > 0) {
Should be checking if the string is empty instead of length.

2021-06-20 19:58 UTC, closed without merging