Spaupdate01
EQEmu/Server pull request #1454
Opened 2021-07-13 15:51 UTC by KayenEQ

Implemented various new spell effects. (7/13/21)

SE_DS_Mitigation_Amount		467 
Modify incoming damage shield damage by percentage. 
Note: Negative value is used to decrease DS (ie. -50 will reduce incoming DS by 50%)

SE_DS_Mitigation_Percentage		468
Modify incoming damage shield damage by flat amount. 
Note: Negative value is used to decrease DS (ie. -500 will reduce flat 500 pts of DS)

SE_Double_Backstab_Front		        473  - Chance to double backstab from front

SE_Critical_Melee_Damage_Mod_Max	496 - increase or decrease by percent critical damage (not stackable)

SE_Melee_Damage_Position_Mod	503 
increase/decreases melee damage by percent base1 based on your position base2 0=back 1=front (not stackable)

SE_Damage_Taken_Position_Mod	505
increase/decreases melee damage taken by percent base1 based on your position base2 0=back 1=front (not stackable)

SE_Health_Transfer				509 
Consume base2 % of Hit Points to Damage for base % of Hit Points
Ie. Lifeburn for damage or Act of Valor for healing
Note: Functional for AOE effects. Ie. Act of Valor 2

SE_AC_Avoidance_Max_Percent        515  -stackable avoidance modifier
SE_AC_Mitigation_Max_Percent	  516  -stackable defense modifier
SE_Attack_Accuracy_Max_Percent	  518  - stackable accuracy modifier

SE_Endurance_Absorb_Pct_Damage	521
Absorb Damage using Endurance: base1 % (base2 End per 1 HP)
Note: Both base1 and base2 need to be divided by 100 for actual value

SE_Instant_Mana_Pct			522  
SE_Instant_Endurance_Pct		523  
Extracts 'base1' percent of your maximum mana/endurance, or 'max', whichever is lower.

SE_Duration_HP_Pct			524 
SE_Duration_Mana_Pct			525
SE_Duration_Endurance_Pct		526 
Consumes 'base1' % of your maximum health/mana/endurance every 6 seconds. 'max' is maximum amount that can be consumed per tic.
Note: Can be used as a heal/gain % by setting the base1 value to a positive.

2021-07-13 20:38 UTC, MidnightMusicClub commented
Are these reversed or am I reading this wrong? 

SE_DS_Mitigation_Amount 467
Modify incoming damage shield damage by percentage.
Note: Negative value is used to decrease DS (ie. -50 will reduce incoming DS by 50%)

SE_DS_Mitigation_Percentage 468
Modify incoming damage shield damage by flat amount.
Note: Negative value is used to decrease DS (ie. -500 will reduce flat 500 pts of DS)

2021-07-13 23:22 UTC, mackal commented
> Are these reversed or am I reading this wrong?

Description yes, implementation no.

2021-07-14 04:39 UTC, mackal requested changes

2021-07-14 04:39 UTC, mackal commented on common/spdat.h
> +#define SE_DS_Mitigation_Amount			467 // implemented - Modify incoming damage shield damage by percentage
Comments swapped

2021-07-14 04:39 UTC, mackal commented on zone/mob.cpp
> +	Shout("Mod 1 %i", critDmg_mod);
Remove shout

2021-07-14 04:39 UTC, mackal commented on zone/mob.cpp
> +	Shout("Mod 2 %i", critDmg_mod);
Remove shout

2021-07-14 10:48 UTC, KayenEQ commented
Fixed description for the DS related affects .

2021-07-14 15:26 UTC, mackal approved these changes

2021-07-15 03:14 UTC, mackal approved these changes

2021-07-15 03:15 UTC, merged