New SPA focus effects and focus limits
EQEmu/Server pull request #1462
Opened 2021-07-20 15:34 UTC by KayenEQ

Implemented various new focus effects and focus limiters (7/20/21)

- Added basic standardized focus and limit descriptions to source in spdat.h, on other areas of relevance. Should improve
understandability of the effects. @Fc = Focus @Ff = Focus Limiters
- Minor fixes to  a couple of AA spell limits
---------------------------------------------------------------------->
Foucus Effects

SE_Fc_Amplify_Mod 507  On Caster, damage-heal-dot mod pct, base: pct

SE_Fc_Amplify_Amt 508 On Caster, damage-heal-dot mod flat amt, base: amt

SE_Fc_ResistIncoming 510 On Target, resist modifier, base: amt 
Note: 2 pts = 1% resist mod +/-

SE_Fc_CastTimeMod2 500  On Caster, cast time mod pct, base: pct

SE_Fc_CastTimeAmt  501  On Caster, cast time mod flat amt, base: milliseconds. 
Note: There is no restriction to much this can lower spell time, if lowered beyond 0, then will instant cast.

---------------------------------------------------------------------->
Foucs Limiters

SE_Ff_DurationMax	 495 Max duration of spell that can be focused, base: tics

SE_Ff_ReuseTimeMin  490 Minimum recast time of a spell that can be focused, base: recast time

SE_Ff_ReuseTimeMax  491 Max recast time of a spell that can be focused, base: recast time

SE_Ff_Endurance_Min 492 Minimum endurance cost of a spell that can be focused, base: endurance cost

SE_Ff_Endurance_Max 493 Max endurance cost of a spell that can be focused, base: endurance cost

SE_Ff_Value_Min 479 Minimum base value of a spell that can be focused, base: spells to be focused base1 value

SE_Ff_Value_Max 480 Max base value of a spell that can be focused, base: spells to be focused base1 value

SE_Ff_Override_NotFocusable	 460 Allow spell to be focused event if flagged with 'not_focusable' in spell table, base: 1

2021-07-21 07:05 UTC, splose commented
Will test these tomorrow.

492/493 and 500/501 will be very helpful for the Synergy AA's I ported over. Some of the melee's are held together with sticks and bubblegum at the moment. :heart:

2021-07-23 08:39 UTC, splose approved these changes

2021-07-26 16:27 UTC, mackal commented
This looks fine, but I'm a bit concerned with stacking order of the new SPA 500 and 501, if anyone can give definitive proof that would be good. (looks like easiest test would be level 110 bard AA Quick Time, just blow the AA in a buff suspend zone and check how the cast time changes removing gear etc)

2021-07-27 05:38 UTC, Akkadius commented
This looks dope!

Per our DM conversation; we'll jump on a call to discuss some of the items you were asking about

2021-07-27 19:55 UTC, mackal commented on zone/mob.cpp
> +	casttime -= cast_reducer_amt;
Until I can get around to proving this happens at a different time, I think I'm gonna say this is fine.

2021-07-30 17:08 UTC, Akkadius commented on zone/spell_effects.cpp
> +
Missing breaks in a lot of these cases

2021-07-30 17:11 UTC, Akkadius requested changes
Minor changes, LGTM

2021-07-30 17:47 UTC, KayenEQ commented on zone/spell_effects.cpp
> +
resolved.

2021-08-01 22:17 UTC, Akkadius approved these changes

2021-08-01 22:45 UTC, merged