Update SPA 339 SE_TriggerOnCast
EQEmu/Server pull request #1478
Opened 2021-07-30 15:03 UTC by KayenEQ

Rewrote the functions that handle the focus effect SPA 339 SE_TriggerOnCast
As reminder, the effect works as a focus that gives a chance to cast an additional spell whenever a spell is cast is conditions are met. Base1: Chance Base2:  spell_id

This focus was not coded consistently to how other focus effects are checked. There is no longer an arbitrary max number focuses with this effect that a player can have. Overall it works well now, fits with rest of foci code, and is easier to manage.

Also added #command resetdisc_timer
usage: #resetdisc_timer [all | timer_id]

2021-07-30 16:50 UTC, Akkadius commented on zone/command.cpp
> +	Client *target = nullptr;
Put else here `c->GetTarget()->CastToClient()`

2021-07-30 16:50 UTC, Akkadius commented on zone/command.cpp
> +		c->ResetDisciplineTimer(timer_id);;
Extra semicolon

2021-07-30 16:52 UTC, Akkadius commented on zone/command.cpp
> +		c->Message(Chat::White, "Reset of disc timer %i for %s", timer_id, c->GetName());
If you ever wanted to, you can use our new fmt library for this

```cpp
fmt::format("Reset of disc timer {} for {}", timer_id, c->GetName()).c_str()
```

2021-07-30 16:56 UTC, Akkadius commented on zone/spell_effects.cpp
> +	if (IsBardSong(spell_id))
Brackets here

2021-07-30 16:56 UTC, Akkadius commented on zone/spell_effects.cpp
> +	uint16 focusspellid = 0;
`snake_case` eg `focus_spellid`

2021-07-30 16:57 UTC, Akkadius commented on zone/spell_effects.cpp
> +
remove extra newlines

2021-07-30 16:57 UTC, Akkadius commented on zone/spell_effects.cpp
> +	if  (IsClient() && itembonuses.FocusEffects[type]) {
extra space

2021-07-30 16:57 UTC, Akkadius commented on zone/spell_effects.cpp
> +
newline

2021-07-30 16:57 UTC, Akkadius commented on zone/spell_effects.cpp
> +			if (!ins)
bracket

2021-07-30 16:58 UTC, Akkadius commented on zone/spell_effects.cpp
> +			TempItem = ins->GetItem();
`snake_case`

2021-07-30 16:58 UTC, Akkadius commented on zone/spell_effects.cpp
> +				if (!IsEffectInSpell(focusspellid, SE_TriggerOnCast))
brackets

2021-07-30 16:59 UTC, Akkadius commented on zone/spell_effects.cpp
> +					const EQ::ItemData* TempItemAug = aug->GetItem();
`snake_case` `temp_item_aug`

2021-07-30 17:01 UTC, Akkadius commented on zone/spell_effects.cpp
> +					const EQ::ItemData* TempItemAug = aug->GetItem();
Use this directly `aug->GetItem()`

2021-07-30 17:03 UTC, Akkadius commented on zone/spell_effects.cpp
> +		for (buff_slot = 0; buff_slot < buff_max; buff_slot++) {
Inline `int buff_slot = 0`

Inline `GetMaxTotalSlots()`

2021-07-30 17:03 UTC, Akkadius commented on zone/spell_effects.cpp
> +
Brackets and newlines in here

2021-07-30 17:04 UTC, Akkadius commented on zone/spell_effects.cpp
> +		Mob* target = nullptr;
Just inline target 

```
Mob* target = GetTarget();
```

2021-07-30 17:04 UTC, Akkadius commented on zone/spell_effects.cpp
> +				EQ::ItemInstance *aug = nullptr;
Inline declaration

```
EQ::ItemInstance *aug = ins->GetAugment(y);
```

2021-07-30 17:06 UTC, Akkadius requested changes
Few comments; LGTM! (We went over this together)

2021-07-30 18:17 UTC, KayenEQ commented
Appreciated the feedback. Syntax updated.

2021-07-31 03:11 UTC, Akkadius commented on zone/spell_effects.cpp
> +		Mob* target = target = GetTarget();
Seems this is a bit of a typo or copy pasta mistake

```cpp
Mob* target = GetTarget();
```

2021-08-01 18:21 UTC, Akkadius commented on zone/command.cpp
> +	Client *target = nullptr;
I took care of this

2021-08-01 18:26 UTC, merged