Add LavaDamage and MinLavaDamage support to ZoneHeader
EQEmu/Server pull request #1540
Opened 2021-09-14 20:14 UTC by Cole-SoD

`
/*Add lava damage variables to zone table*/

ALTER TABLE `zone` ADD `lava_damage` INT(11) NULL DEFAULT '50' AFTER `underground`, ADD `min_lava_damage` INT(11) NOT NULL DEFAULT '10' AFTER `lava_damage`;
`

2021-09-19 20:17 UTC, Akkadius commented on utils/sql/db_update_manifest.txt
> +9173|2021_09_12_zone_lava_damage.sql|SHOW COLUMNS from `zone` WHERE field = 'lava_damage' or field = 'min_lava_damage'|empty|
We only need to check for one column here

2021-09-19 20:18 UTC, Akkadius approved these changes

2021-09-19 20:18 UTC, Akkadius commented
Minor comment. Was this tested?

2021-09-20 21:37 UTC, Cole-SoD commented
> Minor comment. Was this tested?
> 
> Otherwise looks good! Thanks for putting in the effort to put this up

This was not tested. 

> Minor comment. Was this tested?
> 
> Otherwise looks good! Thanks for putting in the effort to put this up

Not tested. I installed EQEmu locally to test just today. The auto updating of the DB is not working, few errors there

2021-09-20 22:42 UTC, Cole-SoD commented
> Minor comment. Was this tested?
> 
> Otherwise looks good! Thanks for putting in the effort to put this up

![image](https://user-images.githubusercontent.com/90719745/134085916-85d1cb75-509b-4a3d-9879-fcf6910b3baa.png)

Tested locally. I assume you run the DB queries, and when someone's local binaries are updated they automatically pull the database changes using eqemu_server.pl.

2021-09-22 21:31 UTC, Akkadius commented
> > Minor comment. Was this tested?
> > Otherwise looks good! Thanks for putting in the effort to put this up
> 
> Not tested. I installed EQEmu locally to test just today. The auto updating of the DB is not working, few errors there. (I am just assuming that the binary makes changes to the database structure?)

Auto update won't work until things are merged. The manifest gets pulled from master 

`eqemu_server.pl` is what pulls down the manifest and conditionally updates your database based on the compiled binary database version that comes back from the `world` binary

2021-09-22 21:32 UTC, Akkadius commented
> > Minor comment. Was this tested?
> > Otherwise looks good! Thanks for putting in the effort to put this up
> 
> ![image](https://user-images.githubusercontent.com/90719745/134085916-85d1cb75-509b-4a3d-9879-fcf6910b3baa.png)
> 
> Tested locally, this is skyfire with 100 min_lava_damage and 500 lava_damage. (Original damage was 45 with default values) I assume you run the DB queries, and when someone's local binaries are updated that will automatically pull the database changes using eqemu_server.pl.

Correct and the manifest is in master

2021-09-22 21:40 UTC, Akkadius commented on utils/sql/db_update_manifest.txt
> +9173|2021_09_12_zone_lava_damage.sql|SHOW TABLES LIKE 'lava_damage'|empty|
This is not going to work

Try something like this 

```sql
SHOW COLUMNS FROM `zone` LIKE 'lava_damage'
```

Also your filename does not match what is committed 

Manifest `2021_09_12_zone_lava_damage.sql` vs File `2021_09_14_zone_lava_damage.sql`

2021-09-22 21:41 UTC, Akkadius requested changes
Left a few comments

2021-09-24 10:56 UTC, Kinglykrab approved these changes

2021-09-29 23:45 UTC, mackal approved these changes

2021-09-30 16:44 UTC, Akkadius approved these changes

2021-09-30 16:44 UTC, merged