[Rule] Added rule to disable SPA 173 from making player immune to enrage.
EQEmu/Server pull request #1897
Opened 2021-12-22 01:28 UTC by KayenEQ

Rule disables live like feature that if you have SPA 173 SE_RiposteChance it makes the player immune to NPC enrage.
True by default, set to false to disable.

2021-12-22 01:58 UTC, joligario requested changes

2021-12-22 01:58 UTC, joligario commented on common/ruletypes.h
> +RULE_BOOL(Combat, ImmuneToEnargeFromRiposteSpellEffect, true, "Set to false to disable SPA 173 SE_RiposteChance from making those with the effect on them immune to enrage")
"Enarge" vs "Enrage"

2021-12-22 02:43 UTC, Dhaymion commented
I like it!  😄

2021-12-22 18:05 UTC, Kinglykrab approved these changes
Looks good barring typo.

2021-12-23 13:31 UTC, KayenEQ commented on common/ruletypes.h
> +RULE_BOOL(Combat, ImmuneToEnargeFromRiposteSpellEffect, true, "Set to false to disable SPA 173 SE_RiposteChance from making those with the effect on them immune to enrage")
I am enarged that I made that mistake.

2021-12-23 20:21 UTC, Akkadius commented on common/ruletypes.h
> +RULE_BOOL(Combat, ImmuneToEnargeFromRiposteSpellEffect, true, "Set to false to disable SPA 173 SE_RiposteChance from making those with the effect on them immune to enrage")
LOL

2021-12-23 20:21 UTC, Akkadius approved these changes

2021-12-23 20:21 UTC, merged