[Bug Fix] Resolve issue with max buff count being 25 in ROF2.
EQEmu/Server pull request #2800
Opened 2023-01-27 21:48 UTC by Kinglykrab

# Notes
- This allows ROF2 to properly utilize their max buff count.
- May cause issues with older clients.

2023-01-27 21:56 UTC, Akkadius requested changes
Let's make sure we've done testing with different clients on this change

2023-01-28 00:37 UTC, Natedog2012 commented
> Let's make sure we've done testing with different clients on this change

The encodes should keep them safe from breaking older clients, but loading up Titanium to see

2023-01-28 01:07 UTC, Natedog2012 commented
Casting every buff on titanium and got my character up to 26 BuffCount (server side) and no crash from the client

2023-01-28 02:40 UTC, Natedog2012 approved these changes
Seems to work for me on titanium

2023-01-28 23:40 UTC, Akkadius commented
> Seems to work for me on titanium

Thanks for testing @Natedog2012 <3

2023-01-28 23:40 UTC, Akkadius approved these changes

2023-01-28 23:40 UTC, merged