Fix for undefined MySQL library behavior.
EQEmu/Server pull request #2834
Opened 2023-02-06 00:15 UTC by KimLS

The MYSQL structure in the MySQL C api is not copy aware. This isn't enforced because, well, C doesn't enforce anything really. 
See: [MySQL Structures](https://dev.mysql.com/doc/c-api/8.0/en/c-api-data-structures.html)

This changes the copy of an existing connection to instead create a second backup connection with the same data as what is being copied.  This does introduce another connection into the mix which are a limited resource but given the potential seriousness of the bug in question it seems like a fair tradeoff for now.  

Long term we can rewrite the dbcore class to use a underlying pointer instead of a pinned in place variable.

2023-02-06 00:44 UTC, KimLS commented
Gonna change some things up to get rid of the double connection, have to rewrite a bit of db core.  Don't merge yet.

2023-02-06 23:57 UTC, Akkadius requested changes
Awaiting pointer changes

2023-02-07 07:31 UTC, KimLS commented
A few changes, have to test make sure they work.  Also I noticed we're not sharing the mutex that protects the connection pointer so have to think up a solution for that. 

(Sorry it's not all at once I'm doing this as I have time at night)

2023-02-25 00:08 UTC, Akkadius commented
Synced up with KLS

We agreed that a mutex should be shared across the database instances because they share the same underlying connection. This protects from concurrency / thread-safety issues.

**Reproduced Problem**

![image](https://user-images.githubusercontent.com/3319450/221323646-263367cd-0633-433c-b7e3-653664104d32.png)

**Fixed, Running for several minutes**

https://user-images.githubusercontent.com/3319450/221323677-db5cf08a-eab1-405d-b7ba-21fe5122ff74.mp4

2023-02-25 00:08 UTC, Akkadius approved these changes

2023-02-25 02:14 UTC, Akkadius commented
Tested booting up all servers, logging in game, everything works as expected

2023-02-25 02:14 UTC, merged