[Cleanup] Cleanup race constants and references.
EQEmu/Server pull request #3763
Opened 2023-12-13 03:55 UTC by Kinglykrab

# Notes
- All race constants have been converted to an enumerator.
- Race bitmask contants have been converted to an enumerator.
- Race methods have been cleaned up and consolidated as best as possible.
- All references to race use the use enumerator.

2023-12-15 05:13 UTC, Akkadius commented on common/eq_packet_structs.h
> -/*0008*/	uint32	MercSubType;		// From dbstr_us.txt - 330020105^23^Race: Guktan<br>Type: Healer<br>Confidence: High<br>Proficiency: Apprentice, Tier V...
This file got hit with a find/replace

Can revert it via `git checkout common/eq_packet_structs.h master`

2023-12-15 05:14 UTC, Akkadius commented on common/patches/rof2_structs.h
> -/*0008*/ uint32 MercSubType; // From dbstr_us.txt - 330020105^23^Race: Guktan<br>Type: Healer<br>Confidence: High<br>Proficiency: Apprentice, Tier V...
This file as well

2023-12-15 05:14 UTC, Akkadius commented on common/patches/rof_structs.h
> -/*0008*/ uint32 MercSubType; // From dbstr_us.txt - 330020105^23^Race: Guktan<br>Type: Healer<br>Confidence: High<br>Proficiency: Apprentice, Tier V...
This file as well

2023-12-15 05:14 UTC, Akkadius commented on common/patches/sod_structs.h
> -/*0008*/	uint32	MercSubType;		// From dbstr_us.txt - 330020105^23^Race: Guktan<br>Type: Healer<br>Confidence: High<br>Proficiency: Apprentice, Tier V...
This file as well

2023-12-15 05:15 UTC, Akkadius commented on common/patches/uf_structs.h
> -/*0008*/	uint32	MercSubType;		// From dbstr_us.txt - 330020105^23^Race: Guktan<br>Type: Healer<br>Confidence: High<br>Proficiency: Apprentice, Tier V...
This file as well

2023-12-16 01:46 UTC, Akkadius commented on zone/bot_command.cpp
> -			"Bot Created | Name: {} ID: {} Race: {} Class: {}",
extra colon here

2023-12-16 01:49 UTC, Akkadius commented on zone/client.cpp
> -	if (race >= RT_FROGLOK_3) {
This is a change in behavior

`RT_FROGLOG_3` was `330` and `Race::Froglok` is `26`

2023-12-16 01:53 UTC, Akkadius commented on zone/common.h
> -	uint32	MercSubType;			// From dbstr_us.txt - 330020105^23^Race: Guktan<br>Type: Healer<br>Confidence: High<br>Proficiency: Apprentice, Tier V...
Find / replace mistake

2023-12-16 01:56 UTC, Akkadius commented on zone/gm_commands/set/gender.cpp
> -		c->Message(Chat::White, "Genders: 0 = Male, 1 = Female, 2 = Neuter");
Looks like several places caught a string replace of `Genders` to `Gender`

2023-12-16 01:56 UTC, Akkadius commented on zone/gm_commands/set/gender.cpp
> -		c->Message(Chat::White, "Genders: 0 = Male, 1 = Female, 2 = Neuter");
Looks like several places caught a string replace of `Genders` to `Gender`

2023-12-16 01:58 UTC, Akkadius commented on zone/mob.cpp
> -			DialogueWindow::TableCell(fmt::format("Race: {}", GetPlayerRaceAbbreviation(GetBaseRace()))) +
Extra colon

2023-12-16 01:58 UTC, Akkadius commented on zone/mob.cpp
> -			"Level: {} Class: {} ({}) Race: {} ({}) Damage Shield: {}/{} Size: {:.1f} Run Speed: {} Weight: {:.1f}/{}",
Extra colon

2023-12-16 01:58 UTC, Akkadius commented on zone/mob.cpp
> -			"Base Race: {} ({}) Gender: {} ({}) Base Gender: {} ({}) Texture: {} Helmet Texture: {}",
Extra colon

2023-12-16 02:01 UTC, Akkadius commented on zone/zonedb.h
> -	uint32	MercSubType;			// From dbstr_us.txt - 330020105^23^Race: Guktan<br>Type: Healer<br>Confidence: High<br>Proficiency: Apprentice, Tier V...
Errant find/replace

2023-12-16 02:22 UTC, Akkadius commented
Rebased against master since there were quite a few merge conflicts

2023-12-16 03:40 UTC, Akkadius commented
This is a nice code cleanup PR. I like the changes. 

However, there's a ton here and high risk of regression that can be hard to chase down and in multiple places so let's try and be as accurate as possible.

What makes review difficult is this isn't just changing constants, it's also changing logic and adding / removing cases in different places.

Even if I were to look this 10 times over and someone else, I don't have confidence in catching everything so I wrote a quick Go program that would load the old constants and the new and compare them. 

The problem again lies is that we're not 1:1 changing everything as some switch statements have multiple added new lines so the matching change may be another race.

On this branch if we run `git diff --word-diff origin/master`

We get contents like 

```diff
                case [-RT_BANNER_5:-]{+Race::Froglok:+}
                case [-RT_BANNER_6:-]{+Race::FroglokGhoul:+}
                case [-RT_BANNER_7:-]{+Race::Froglok2:+}
```

**Matches (253)**

```
matched file [b/common/faction.cpp] added [Race::DarkElf] value (6) removed [DARK_ELF] value (6)
matched file [b/common/faction.cpp] added [Race::Barbarian] value (2) removed [BARBARIAN] value (2)
matched file [b/common/faction.cpp] added [Race::DarkElf] value (6) removed [DARK_ELF] value (6)
matched file [b/common/faction.cpp] added [Race::Ogre] value (10) removed [OGRE] value (10)
matched file [b/common/faction.cpp] added [Race::Troll] value (9) removed [TROLL] value (9)
matched file [b/common/faction.cpp] added [Race::Human] value (1) removed [HUMAN] value (1)
matched file [b/common/faction.cpp] added [Race::Barbarian] value (2) removed [BARBARIAN] value (2)
matched file [b/common/faction.cpp] added [Race::HalfElf] value (7) removed [HALF_ELF] value (7)
matched file [b/common/faction.cpp] added [Race::Gnome] value (12) removed [GNOME] value (12)
matched file [b/common/faction.cpp] added [Race::Halfling] value (11) removed [HALFLING] value (11)
matched file [b/common/faction.cpp] added [Race::WoodElf] value (4) removed [WOOD_ELF] value (4)
matched file [b/common/faction.cpp] added [Race::Erudite] value (3) removed [ERUDITE] value (3)
matched file [b/common/faction.cpp] added [Race::Dwarf] value (8) removed [DWARF] value (8)
matched file [b/common/faction.cpp] added [Race::HighElf] value (5) removed [HIGH_ELF] value (5)
matched file [b/common/faction.cpp] added [Race::VahShir] value (130) removed [VAHSHIR] value (130)
matched file [b/common/faction.cpp] added [Race::Iksar] value (128) removed [IKSAR] value (128)
matched file [b/common/races.cpp] added [Race::GiantBat] value (34) removed [RT_BAT] value (34)
matched file [b/common/races.cpp] added [Race::Bat] value (260) removed [RT_BAT_2] value (260)
matched file [b/common/races.cpp] added [Race::Bat2] value (416) removed [RT_BAT_3] value (416)
matched file [b/common/races.cpp] added [Race::FayDrake] value (154) removed [RT_FAY_DRAKE] value (154)
matched file [b/common/races.cpp] added [Race::GuardOfJustice] value (251) removed [RT_GUARD_OF_JUSTICE] value (251)
matched file [b/common/races.cpp] added [Race::Kraken] value (315) removed [RT_KRAKEN] value (315)
matched file [b/common/races.cpp] added [Race::Human] value (1) removed [RACE_HUMAN_1] value (1)
matched file [b/common/races.cpp] added [Race::Barbarian] value (2) removed [RACE_BARBARIAN_2] value (2)
matched file [b/common/races.cpp] added [Race::Erudite] value (3) removed [RACE_ERUDITE_3] value (3)
matched file [b/common/races.cpp] added [Race::WoodElf] value (4) removed [RACE_WOOD_ELF_4] value (4)
matched file [b/common/races.cpp] added [Race::HighElf] value (5) removed [RACE_HIGH_ELF_5] value (5)
matched file [b/common/races.cpp] added [Race::DarkElf] value (6) removed [RACE_DARK_ELF_6] value (6)
matched file [b/common/races.cpp] added [Race::HalfElf] value (7) removed [RACE_HALF_ELF_7] value (7)
matched file [b/common/races.cpp] added [Race::Dwarf] value (8) removed [RACE_DWARF_8] value (8)
matched file [b/common/races.cpp] added [Race::Troll] value (9) removed [RACE_TROLL_9] value (9)
matched file [b/common/races.cpp] added [Race::Ogre] value (10) removed [RACE_OGRE_10] value (10)
matched file [b/common/races.cpp] added [Race::Halfling] value (11) removed [RACE_HALFLING_11] value (11)
matched file [b/common/races.cpp] added [Race::Gnome] value (12) removed [RACE_GNOME_12] value (12)
matched file [b/common/races.cpp] added [Race::Iksar] value (128) removed [RACE_IKSAR_128] value (128)
matched file [b/common/races.cpp] added [Race::VahShir] value (130) removed [RACE_VAH_SHIR_130] value (130)
matched file [b/common/races.cpp] added [Race::Drakkin] value (522) removed [RACE_DRAKKIN_522] value (522)
matched file [b/world/client.cpp] added [Race::Barbarian] value (2) removed [BARBARIAN] value (2)
matched file [b/world/client.cpp] added [Race::Dwarf] value (8) removed [DWARF] value (8)
matched file [b/world/client.cpp] added [Race::Erudite] value (3) removed [ERUDITE] value (3)
matched file [b/world/client.cpp] added [Race::HalfElf] value (7) removed [HALF_ELF] value (7)
matched file [b/world/client.cpp] added [Race::HighElf] value (5) removed [HIGH_ELF] value (5)
matched file [b/world/client.cpp] added [Race::Human] value (1) removed [HUMAN] value (1)
matched file [b/world/client.cpp] added [Race::Ogre] value (10) removed [OGRE] value (10)
matched file [b/world/client.cpp] added [Race::Troll] value (9) removed [TROLL] value (9)
matched file [b/world/client.cpp] added [Race::Drakkin] value (522) removed [DRAKKIN] value (522)
matched file [b/world/client.cpp] added [Race::DarkElf] value (6) removed [DARK_ELF] value (6)
matched file [b/world/client.cpp] added [Race::Gnome] value (12) removed [GNOME] value (12)
matched file [b/world/client.cpp] added [Race::Halfling] value (11) removed [HALFLING] value (11)
matched file [b/world/client.cpp] added [Race::Iksar] value (128) removed [IKSAR] value (128)
matched file [b/world/client.cpp] added [Race::WoodElf] value (4) removed [WOOD_ELF] value (4)
matched file [b/world/client.cpp] added [Race::VahShir] value (130) removed [VAHSHIR] value (130)
matched file [b/world/client.cpp] added [Race::Barbarian] value (2) removed [BARBARIAN] value (2)
matched file [b/world/client.cpp] added [Race::DarkElf] value (6) removed [DARK_ELF] value (6)
matched file [b/world/client.cpp] added [Race::Dwarf] value (8) removed [DWARF] value (8)
matched file [b/world/client.cpp] added [Race::Erudite] value (3) removed [ERUDITE] value (3)
matched file [b/world/client.cpp] added [Race::Gnome] value (12) removed [GNOME] value (12)
matched file [b/world/client.cpp] added [Race::HalfElf] value (7) removed [HALF_ELF] value (7)
matched file [b/world/client.cpp] added [Race::Halfling] value (11) removed [HALFLING] value (11)
matched file [b/world/client.cpp] added [Race::HighElf] value (5) removed [HIGH_ELF] value (5)
matched file [b/world/client.cpp] added [Race::Human] value (1) removed [HUMAN] value (1)
matched file [b/world/client.cpp] added [Race::Iksar] value (128) removed [IKSAR] value (128)
matched file [b/world/client.cpp] added [Race::Ogre] value (10) removed [OGRE] value (10)
matched file [b/world/client.cpp] added [Race::Troll] value (9) removed [TROLL] value (9)
matched file [b/world/client.cpp] added [Race::WoodElf] value (4) removed [WOOD_ELF] value (4)
matched file [b/world/client.cpp] added [Race::VahShir] value (130) removed [VAHSHIR] value (130)
matched file [b/world/client.cpp] added [Race::Drakkin] value (522) removed [DRAKKIN] value (522)
matched file [b/zone/bot.cpp] added [Race::Ogre] value (10) removed [OGRE] value (10)
matched file [b/zone/bot.cpp] added [Race::Troll] value (9) removed [TROLL] value (9)
matched file [b/zone/bot.cpp] added [Race::VahShir] value (130) removed [VAHSHIR] value (130)
matched file [b/zone/bot.cpp] added [Race::Barbarian] value (2) removed [BARBARIAN] value (2)
matched file [b/zone/bot.cpp] added [Race::HalfElf] value (7) removed [HALF_ELF] value (7)
matched file [b/zone/bot.cpp] added [...]

2023-12-16 03:47 UTC, Akkadius commented
For this PR I'm going to propose we do 1 branch with 1:1 of constants changes and then separate introduce a PR which proposes logic changes, additional items to switch statements.

I'll cut a branch that does a 1:1 automatically using code

2023-12-16 04:03 UTC, hgtw reviewed
I didn't finish but the biggest issue is the Froglok issue and the change in behavior of those appearance functions with the luclin flag. The change to a map might need a second look for performance since it looks like it's in some heavy combat code. I'll try to look at this more when I can

2023-12-16 06:35 UTC, Akkadius requested changes
Spent a few hours reviewing and then ultimately cutting a branch to help out since I'm sure this PR was a lot of work

https://github.com/EQEmu/Server/pull/3773

2023-12-17 01:49 UTC, closed without merging