[Cleanup] Add Generic Inventory Slot IDs for Loops
EQEmu/Server pull request #4358
Opened 2024-05-29 01:11 UTC by Kinglykrab

# Description
- Adds `EQ::InventoryProfile;:GetInventorySlotIDs()` which returns all inventory slots in a vector for easy looping.
- This allows us to reduce quite a bit of code duplication.

## Type of Change
- [X] New feature

# Checklist
- [X] I have tested my changes
- [X] I have performed a self-review of my code. Ensuring variables, functions and methods are named in a human-readable way, comments are added only where naming of variables, functions and methods can't give enough context.
- [X] I own the changes of my code and take responsibility for the potential issues that occur

2024-06-02 00:15 UTC, Akkadius commented on common/inventory_profile.cpp
> +				LogInfo("Adding slot ID [{}]", slot_id);
Probably don't want to leave this in here as LogInfo

2024-06-17 23:18 UTC, joligario requested changes
A few comments. I think this deserves some good testing with a character with partial, full, and no inventory items across the spectrum. This should include stacks, charges, etc.

2024-06-17 23:18 UTC, joligario commented on common/inventory_profile.cpp
> +		{ InventoryFilter::Personal,   { EQ::invbag::GENERAL_BAGS_BEGIN,     EQ::invbag::GENERAL_BAGS_BEGIN }},
GENERAL_BAGS_END

2024-06-17 23:18 UTC, joligario commented on common/inventory_profile.cpp
> +		{ InventoryFilter::SharedBank, { EQ::invbag::SHARED_BANK_BAGS_BEGIN, EQ::invbag::SHARED_BANK_BAGS_END }},
I know its forgiving, but we can remove final comma

2024-06-17 23:18 UTC, joligario commented on zone/client.cpp
> +			int16 charges    = item->IsStackable() ? item->GetCharges() : 0;
Referenced above. I know you didn't write it, but we should be consistent with charges.

2024-07-03 01:14 UTC, joligario approved these changes
Looks good. A deliberate testing round is still warranted.

2024-07-08 03:48 UTC, closed without merging